# Generated by Django 3.1.11 on 2021-10-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=264, unique=True)),
                ('name', models.CharField(max_length=264)),
                ('fname', models.CharField(max_length=264)),
                ('gender', models.CharField(max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('pincode', models.CharField(max_length=264)),
                ('postoffice', models.CharField(max_length=264, unique=True)),
                ('district', models.CharField(max_length=264)),
                ('state', models.CharField(max_length=264)),
                ('mno', models.CharField(max_length=264, unique=True)),
                ('adhar', models.CharField(max_length=264, unique=True)),
                ('email', models.CharField(max_length=264)),
            ],
        ),
    ]
