# Generated by Django 3.1.11 on 2021-10-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211017_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='mid',
            field=models.AutoField(default=101, primary_key=True, serialize=False),
        ),
    ]
