# Generated by Django 3.1.11 on 2021-10-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211017_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mid',
            field=models.IntegerField(default=101, primary_key=True, serialize=False),
        ),
    ]
