# Generated by Django 3.1.11 on 2021-10-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211017_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, default=101, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='mid',
            field=models.IntegerField(default=101),
        ),
    ]
