# Generated by Django 3.1.11 on 2021-10-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211017_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='postoffice',
            field=models.CharField(max_length=264),
        ),
    ]
